"""posts table

Revision ID: 5062b5439ce8
Revises: 21393a884859
Create Date: 2025-10-17 00:39:45.672353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5062b5439ce8'
down_revision = '21393a884859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensajes_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensajes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comentarios_timestamp'))
        batch_op.drop_index(batch_op.f('ix_comentarios_user_id'))

    op.drop_table('comentarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comentarios_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comentarios_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensajes_user_id'))
        batch_op.drop_index(batch_op.f('ix_mensajes_timestamp'))

    op.drop_table('mensajes')
    # ### end Alembic commands ###
